export const HeroSectionData = {
  decription:
    "Based in Dhaka, Bangladesh 📍, Im a passionate developer crafting seamless, dynamic web experiences. From sleek e-commerce platformsto interactive applications, I turn ideas into reality. Dive into my portfolio and let’s create something extraordinary together!",
};
export const skills: string[] = [
  "Html5",
  "Css",
  "Sass",
  "Responsive Design",
  "Tailwind CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "Django",
  "Java",
  "C++",
  "C",
  "React",
  "NextJs",
  "GitHub",
  "NodeJs",
  "Express",
  "Postman",
  "REST APIs",
  "Object-Oriented Programming",
  "Prisma",
  "SQL",
  "PostgreSQL",
  "Firebase",
  "MongoDB",
  "RESTful APIs",
  "React Native",
  "Redux",
  "Web Development",
  "Figma",
  "MySQL",
  "Node.js",
  "express.js",
  "Nest.js",
  "Prisma",
];
